# -*- coding: utf-8 -*-
"""17_mechanism.py -- is the free mechanical coefficient (a ~ 0.78, identity says 1) attenuation or real?

Same design and fixed effects as pac/gamelevel.py (main specification, free mechanical coefficient). The term
sum L_full*(price - lam) is split by group, each with its own coefficient; c and s stay common.

If a < 1 were measurement error in lam absorbed unevenly by the fixed effects, it would rise with the share of his
window he played and with his shot volume. If it is like-for-like replacement, it should be lowest for low-usage
role players. Writes results/mechanism.md.
"""
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from pac import gamelevel as G  # noqa: E402
from pac import paths  # noqa: E402



def main():
    A = G.assemble(ft_w=0.44, outcome="tsa", min_apps=10, min_den=4.0)
    M, _ = G.model_for(A)
    y, Z0, Z2, P, ev = A["y"], A["Z0"], A["Z2"], A["P"], A["ev"]
    n = len(y)
    rows, pl = ev["absent_rows"], ev["absent_pl"]
    Lf = P.L_full.values[pl]
    edge = (P.price.values - P.lam.values)[pl]
    phi = (P.n_apps / P.window).values[pl]
    vol = (P.n_apps.values * P.L_full.values * 85.0)[pl]          # approx. TSA in games played (team ~85 TSA/game)
    L = P.L.values[pl]
    splits = [
        ("share of tenure window played", [(">= 0.90", phi >= 0.9), ("0.75-0.90", (phi >= 0.75) & (phi < 0.9)), ("< 0.75", phi < 0.75)]),
        ("shot volume in games played (approx. TSA)", [(">= 1000", vol >= 1000), ("500-1000", (vol >= 500) & (vol < 1000)), ("< 500", vol < 500)]),
        ("share L", [("< 0.18", L < 0.18), ("0.18-0.24", (L >= 0.18) & (L < 0.24)), (">= 0.24", L >= 0.24)]),
        ("sign of his efficiency edge", [("below league", edge > 0), ("at or above league", edge <= 0)]),
    ]
    out = ["# Mechanical coefficient by group\n",
           "Generated by `scripts/17_mechanism.py`. Main specification of `pac/gamelevel.py` with the mechanical term "
           "`sum L_full*(price - lam)` split by group (identity says every coefficient is 1). c and s common.\n"]
    for title, groups in splits:
        Zs = [G.zsum(rows[m], (Lf * edge)[m], n) for _, m in groups]
        b, V = M.fit(y, Zs + [Z0, Z2])
        out.append(f"## {title}\n")
        out.append("| group | absences | coefficient | 95% CI |\n|---|---|---|---|")
        for j, (lab, m) in enumerate(groups):
            se = float(np.sqrt(V[j, j]))
            out.append(f"| {lab} | {int(m.sum()):,} | {b[j]:.3f} | [{b[j] - 1.96 * se:.3f}, {b[j] + 1.96 * se:.3f}] |")
        k = len(groups)
        out.append(f"\ncommon c = {-b[k]:.3f}, s = {-b[k + 1]:.3f}\n")
    txt = "\n".join(out)
    with open(paths.result("mechanism.md"), "w", encoding="utf-8") as f:
        f.write(txt)
    print(txt)


if __name__ == "__main__":
    main()
