# -*- coding: utf-8 -*-
"""20_out_of_sample.py -- out-of-sample test of PAC as a scoring statistic (post-submission validation, 2026-10-02).

1. Estimate the price s ONLY on 1997-98 .. 2014-15 (game-level design, same spec as the main model of pac/gamelevel.py).
2. On 2015-16 .. 2025-26, which the price never saw, measure what teams actually lose per game when a player
   sits (same regression as 12_pac_vs_tsadd.py, test seasons only) and compare with each statistic's per-game value
   of the absent players: TS Points Added (s = 0) and PAC at the training-only s.
3. Year-over-year stability at s = 0.25 (qualified players in consecutive seasons): PPG, TS Added/g, PAC/g.
Writes results/out_of_sample.md and results/out_of_sample.json.

POST-SUBMISSION VALIDATION (2026-10-02). None of these numbers are in the working paper v1.
Self-check: with every season as the test set, the same code must reproduce Table 1 (3.52 lost at 30%+ share).
"""
import json
import os
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from pac import gamelevel as G  # noqa: E402
from pac import paths  # noqa: E402

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
EDGES = [0.0, 0.15, 0.20, 0.25, 0.30, 1.0]
SPLIT = 2015  # test seasons: 2015-16 .. 2025-26


def main():
    vals = []
    for y in G.YEARS:
        with open(paths.pac_season(G.code_of(y)), encoding="utf-8") as f:
            S = pd.DataFrame(json.load(f)["rows"])[["pid", "name", "gp", "poss", "pts", "tsa", "tsadd", "l"]]
        S["season"] = y
        vals.append(S)
    V = pd.concat(vals, ignore_index=True)
    V["pid"] = V.pid.astype("int64")
    V["l"] = V.l.fillna(0)

    A = G.assemble(ft_w=0.44, outcome="tsa", min_apps=10, min_den=4.0)
    tg, P, ev = A["tg"], A["P"], A["ev"]
    n = len(tg)
    season = tg.season.values
    train, test = season < SPLIT, season >= SPLIT
    r_tr = G.run_core(A, mask=train)
    r_te = G.run_core(A, mask=test)
    s_tr, se_tr = r_tr["s_origin"], r_tr["s_origin_se"]
    print(f"s train 1997-{SPLIT - 1}: {s_tr:.3f} (se {se_tr:.3f}); s test-only (for reference): {r_te['s_origin']:.3f}", flush=True)

    V["ppg"] = V.pts / V.gp
    V["tsaddg"] = V.tsadd / V.gp
    V["pac_tr"] = (V.tsadd + V.tsa * s_tr * V.l) / V.gp
    V["pac25"] = (V.tsadd + V.tsa * 0.25 * V.l) / V.gp
    Pm = P[["pid", "season"]].copy()
    Pm["pid"] = Pm.pid.astype("int64")
    Pm = Pm.merge(V[["pid", "season", "ppg", "tsaddg", "pac_tr", "pac25"]], on=["pid", "season"], how="left")

    rows, pl = ev["absent_rows"], ev["absent_pl"]
    Lab = P.L.values[pl]
    in_test = test[rows]
    counts, labs = [], []
    for lo, hi in zip(EDGES[:-1], EDGES[1:]):
        mb = (Lab >= lo) & (Lab < hi) & in_test
        counts.append(np.bincount(rows[mb], minlength=n).astype(float))
        sub = Pm.iloc[pl[mb]]
        labs.append(dict(lo=lo, hi=hi, n=int(mb.sum()), ppg=float(sub.ppg.mean()), tsadd=float(sub.tsaddg.mean()),
                         pac_tr=float(sub.pac_tr.mean()), pac25=float(sub.pac25.mean())))
    M, m = G.model_for(A, mask=test)
    b, Vb = M.fit(tg.pts.values.astype(float)[m], [c[m] for c in counts])

    # self-check: the same regression on ALL seasons must reproduce Table 1 of the paper (30%+ share: 3.52 lost)
    full_counts = []
    for lo, hi in zip(EDGES[:-1], EDGES[1:]):
        mb = (Lab >= lo) & (Lab < hi)
        full_counts.append(np.bincount(rows[mb], minlength=n).astype(float))
    Mf, mf = G.model_for(A)
    bf, _ = Mf.fit(tg.pts.values.astype(float)[mf], [c[mf] for c in full_counts])
    table1 = [round(-x, 2) for x in bf[:len(full_counts)]]
    assert table1 == [-0.39, -0.12, 0.32, 2.0, 3.52], table1
    print("self-check: in-sample Table 1 reproduced", table1, flush=True)

    out = ["# Out-of-sample test of PAC as a scoring statistic\n",
           f"POST-SUBMISSION VALIDATION, 2026-10-02: not part of the working paper v1. Generated by `scripts/20_out_of_sample.py`. Price estimated on 1997-98 to {SPLIT - 1}-{SPLIT % 100:02d} only: "
           f"**s = {s_tr:.3f}** [{s_tr - 1.96 * se_tr:.3f}, {s_tr + 1.96 * se_tr:.3f}]. "
           f"Scored on {SPLIT}-{(SPLIT + 1) % 100:02d} to 2025-26, which the price never saw "
           f"(test-period s, for reference only: {r_te['s_origin']:.3f}).\n",
           "Actual = points per game the team loses per absent rotation player in each share bin (test seasons only; "
           "roster-spell, opponent-season and season-month fixed effects; home / rest / opponent-absence controls; 95% CI "
           "clustered by team-season). The other columns: the absent players' per-game values.\n",
           f"| absent player's share | absences | his PPG | actually lost | TS Points Added | PAC (s = {s_tr:.3f}, out of sample) | PAC (s = 0.25) |",
           "|---|---|---|---|---|---|---|"]
    err = {"tsadd": [], "pac_tr": [], "pac25": []}
    wts, res_rows = [], []
    for j, r in enumerate(labs):
        act, se = -b[j], float(np.sqrt(Vb[j, j]))
        out.append(f"| {r['lo']:.0%}-{r['hi']:.0%} | {r['n']:,} | {r['ppg']:.1f} | **{act:.2f}** [{act - 1.96 * se:.2f}, {act + 1.96 * se:.2f}] | "
                   f"{r['tsadd']:.2f} | {r['pac_tr']:.2f} | {r['pac25']:.2f} |")
        for k in err:
            err[k].append(r[k] - act)
        wts.append(r["n"])
        res_rows.append(dict(r, actual=act, actual_se=se))
    wts = np.array(wts, float)
    mae = {k: float(np.average(np.abs(v), weights=wts)) for k, v in err.items()}
    top = {k: float(v[-1]) for k, v in err.items()}
    out += ["", f"Absence-weighted mean absolute error vs actual: TS Points Added **{mae['tsadd']:.2f}**, "
                f"PAC out of sample **{mae['pac_tr']:.2f}**, PAC at 0.25 {mae['pac25']:.2f} points per game.",
            f"Error at 30%+ share (stat minus actual): TS Points Added {top['tsadd']:+.2f}, PAC out of sample {top['pac_tr']:+.2f}, "
            f"PAC at 0.25 {top['pac25']:+.2f}.\n"]

    # year-over-year stability at s = 0.25, qualified in consecutive seasons
    q = V[(V.gp >= 40) & (V.poss >= 2500)].copy()
    nx = q.copy(); nx["season"] -= 1
    jn = q.merge(nx, on=["pid", "season"], suffixes=("", "_next"))
    yoy = {c: float(jn[c].corr(jn[c + "_next"])) for c in ("ppg", "tsaddg", "pac25")}
    out += ["## Year-over-year stability (s = 0.25)\n",
            f"Qualified (40+ games, 2,500+ possessions) in consecutive seasons, n = {len(jn):,}: "
            f"PPG {yoy['ppg']:.3f}, TS Points Added/g {yoy['tsaddg']:.3f}, PAC/g {yoy['pac25']:.3f}.\n"]
    with open(paths.result("out_of_sample.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    with open(paths.result("out_of_sample.json"), "w", encoding="utf-8") as f:
        json.dump(dict(split=SPLIT, s_train=s_tr, s_train_se=se_tr, s_test_only=r_te["s_origin"], bins=res_rows, mae=mae,
                       err_top=top, yoy=yoy, yoy_n=len(jn)), f, indent=1)
    print("\n".join(out))


if __name__ == "__main__":
    main()
