# -*- coding: utf-8 -*-
"""_pac_scarcity_vs_creation.py -- is the measured price possession scarcity, or losing the player's playmaking?

The price comes from games a player misses. Two things vanish in those games: his shots (their possessions have to be
absorbed by teammates: scarcity) and his playmaking (the shots he creates for others: creation). If the price were mostly
creation, the absence of a playmaker (high AST%) would cost far more than the absence of a pure scorer at the same share.
If it is mostly scarcity, they cost about the same.

Main model of _pac_gamelevel.py, validated hinge schedule, with the absence term split by the absent player's AST%
(tertiles within share bands), plus a continuous AST% interaction. Also prints the worked possession-budget examples.
Writes _pac_scarcity_vs_creation.md.
"""
import json
import os
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _pac_gamelevel as G  # noqa: E402

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
HERE = os.path.dirname(os.path.abspath(__file__))


def main():
    with open(os.path.join(HERE, "_pac_gamelevel_results.json"), encoding="utf-8") as f:
        H = json.load(f)["hinge"]
    s_h, L0 = H["s_h"], H["L0"]
    ast = {}
    for y in G.YEARS:
        rows = G.columnar_rows(G.load_json(f"_nba_pl_adv_{G.code_of(y)}.json")) if hasattr(G, "columnar_rows") else None
        if rows is None:
            with open(os.path.join(HERE, f"_nba_pl_adv_{G.code_of(y)}.json"), encoding="utf-8") as f:
                d = json.load(f)
            keys = list(d.keys())
            nrow = len(d[keys[0]])
            rows = [{k: d[k].get(str(i), d[k].get(i)) if isinstance(d[k], dict) else d[k][i] for k in ("PLAYER_ID", "AST_PCT")} for i in range(nrow)]
        for r in rows:
            try:
                ast[(int(float(r["PLAYER_ID"])), y)] = float(r["AST_PCT"])
            except (TypeError, ValueError):
                pass
    A = G.assemble(ft_w=0.44, outcome="tsa", min_apps=10, min_den=4.0)
    tg, P, ev = A["tg"], A["P"], A["ev"]
    y, Z1 = A["y"], A["Z1"]
    n = len(y)
    P = P.copy()
    P["ast"] = [ast.get((int(p), int(s)), np.nan) for p, s in zip(P.pid, P.season)]
    rows, pl = ev["absent_rows"], ev["absent_pl"]
    Lf, Lab, Aab = P.L_full.values[pl], P.L.values[pl], P.ast.values[pl]
    ok = np.isfinite(Aab)
    hinge = np.maximum(0.0, Lab - L0)
    M, _ = G.model_for(A)
    out = ["# Possession scarcity or lost playmaking?\n", "Generated by `_pac_scarcity_vs_creation.py`.\n",
           f"Absences with AST% available: {ok.sum():,} of {len(ok):,}.\n"]

    # --- split by playmaking tertile within share bands (so groups have the same share distribution)
    bands = [(0.0, 0.18), (0.18, 0.24), (0.24, 1.0)]
    grp = np.full(len(pl), -1)
    for lo, hi in bands:
        m = ok & (Lab >= lo) & (Lab < hi)
        if m.sum() == 0:
            continue
        q1, q2 = np.quantile(Aab[m], [1 / 3, 2 / 3])
        grp[m & (Aab <= q1)] = 0
        grp[m & (Aab > q1) & (Aab <= q2)] = 1
        grp[m & (Aab > q2)] = 2
    Z = [G.zsum(rows[grp == g], (Lf * hinge)[grp == g], n) for g in (0, 1, 2)]
    Zmiss = G.zsum(rows[grp == -1], (Lf * hinge)[grp == -1], n)
    b, V = M.fit(y, Z + [Zmiss], offset=Z1)
    labs = ["pure scorers (lowest third of AST% at their share)", "middle third", "playmakers (highest third of AST%)"]
    out.append("## 1. Price slope by the absent player's playmaking (same share distribution in each group)\n")
    out.append("| absent player | absences | median AST% | slope above threshold | gap at L = 0.30 (pts per attempt) |\n|---|---|---|---|---|")
    for g in range(3):
        m = grp == g
        sl, se = -b[g], float(np.sqrt(V[g, g]))
        out.append(f"| {labs[g]} | {int(m.sum()):,} | {100 * np.median(Aab[m]):.0f}% | {sl:.3f} [{sl - 1.96 * se:.3f}, {sl + 1.96 * se:.3f}] | "
                   f"{sl * (0.30 - L0):.3f} |")
    d02 = -b[2] + b[0]
    se02 = float(np.sqrt(V[0, 0] + V[2, 2] - 2 * V[0, 2]))
    out.append(f"\nPlaymakers minus pure scorers: {d02:+.3f} [{d02 - 1.96 * se02:+.3f}, {d02 + 1.96 * se02:+.3f}] in slope.\n")

    # --- continuous interaction among high-share players
    hi = ok & (Lab >= 0.24)
    ac = np.where(ok, Aab - np.nanmean(Aab[hi]), 0.0)
    Zh = G.zsum(rows, Lf * hinge, n)
    Zha = G.zsum(rows[ok], (Lf * hinge * ac)[ok], n)
    b2, V2 = M.fit(y, [Zh, Zha], offset=Z1)
    sd_hi = float(np.nanstd(Aab[hi]))
    eff = -b2[1] * sd_hi
    se_eff = float(np.sqrt(V2[1, 1])) * sd_hi
    base = -b2[0]
    out.append("## 2. Continuous: how much does one SD more playmaking change the slope?\n")
    out.append(f"- slope at average playmaking for 24%+ players: {base:.3f}")
    out.append(f"- one SD of AST% among 24%+ players = {100 * sd_hi:.1f} points; it changes the slope by **{eff:+.3f} [{eff - 1.96 * se_eff:+.3f}, {eff + 1.96 * se_eff:+.3f}]**, "
               f"i.e. {100 * eff / base:+.0f}% of the slope")
    out.append("")

    # --- worked possession-budget examples (2025-26 league price)
    with open(os.path.join(HERE, "_sv_season_2526.json"), encoding="utf-8") as f:
        lgts = json.load(f)["summary"]["lg_ts"] / 100
    price = 2 * lgts
    def cost(poss, team, ts):
        L = poss / team
        mp = price - s_h * max(0.0, L - L0)
        return L, poss * (2 * ts - price), poss * (2 * ts - mp), 100 * poss * (2 * ts - mp) / team
    out.append(f"## 3. Worked examples (2025-26 league average {100 * lgts:.1f}% TS = {price:.3f} points per shooting possession)\n")
    out.append("| player | share | vs league average (TS Add) | vs measured price (PAC) | PAC per 100 team possessions |\n|---|---|---|---|---|")
    for poss, team, ts in ((40, 100, 0.30), (30, 100, 0.30), (30, 200, 0.30), (30, 100, 0.55), (30, 100, 0.65)):
        L, la, pc, p100 = cost(poss, team, ts)
        out.append(f"| {poss} of {team} possessions at {100 * ts:.0f}% TS | {100 * L:.0f}% | {la:+.1f} | {pc:+.1f} | {p100:+.1f} |")
    txt = "\n".join(out)
    with open(os.path.join(HERE, "_pac_scarcity_vs_creation.md"), "w", encoding="utf-8") as f:
        f.write(txt)
    print(txt)


if __name__ == "__main__":
    main()
