# -*- coding: utf-8 -*-
"""_pac_scarcity_forms.py -- the scarcity-only price in PAC's own functional forms.

Same model as _pac_gamelevel.py (fixed effects, controls, identity offset). The absence terms are split by the absent
player's playmaking (AST% tertile within share bands, as in _pac_scarcity_vs_creation.py), and each group gets PAC's
published form (gap = s*L, through the origin), the free-intercept line, and share bins. Pure scorers' absences remove
their shots but little creation, so their price is the closest measure of possession scarcity alone.
Writes _pac_scarcity_forms.md.
"""
import json, os, sys
import numpy as np
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _pac_gamelevel as G
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
HERE = os.path.dirname(os.path.abspath(__file__))

def main():
    ast = {}
    for y in G.YEARS:
        with open(os.path.join(HERE, f"_nba_pl_adv_{G.code_of(y)}.json"), encoding="utf-8") as f:
            d = json.load(f)
        ids, ap = d["PLAYER_ID"], d["AST_PCT"]
        for k in ids:
            try:
                ast[(int(float(ids[k])), y)] = float(ap[k])
            except (TypeError, ValueError, KeyError):
                pass
    A = G.assemble(ft_w=0.44, outcome="tsa", min_apps=10, min_den=4.0)
    P, ev, y, Z1 = A["P"], A["ev"], A["y"], A["Z1"]
    n = len(y)
    P = P.assign(ast=[ast.get((int(p), int(s)), np.nan) for p, s in zip(P.pid, P.season)])
    rows, pl = ev["absent_rows"], ev["absent_pl"]
    Lf, Lab, Aab = P.L_full.values[pl], P.L.values[pl], P.ast.values[pl]
    grp = np.full(len(pl), -1)
    for lo, hi in ((0.0, 0.18), (0.18, 0.24), (0.24, 1.0)):
        m = np.isfinite(Aab) & (Lab >= lo) & (Lab < hi)
        q1, q2 = np.quantile(Aab[m], [1 / 3, 2 / 3])
        grp[m & (Aab <= q1)] = 0; grp[m & (Aab > q1) & (Aab <= q2)] = 1; grp[m & (Aab > q2)] = 2
    M, _ = G.model_for(A)
    names = ["pure scorers (lowest third AST%)", "middle third", "playmakers (highest third AST%)"]
    out = ["# Scarcity-only price in PAC's own forms\n", "Generated by `_pac_scarcity_forms.py`. Published PAC: gap = 0.25 L.\n",
           "## 1. PAC's published form (gap = s L, through the origin) and the free-intercept line, by the absent player's playmaking\n",
           "All three groups are estimated jointly in one model (each with its own terms), same fixed effects and controls.\n",
           "| absent player | absences | s, through origin (published form) | free intercept c | free slope s | gap at L = 0.30 (free) |",
           "|---|---|---|---|---|---|"]
    Zo = [G.zsum(rows[grp == g], (Lf * Lab)[grp == g], n) for g in range(3)]
    Zc = [G.zsum(rows[grp == g], Lf[grp == g], n) for g in range(3)]
    Zo_miss = G.zsum(rows[grp == -1], (Lf * Lab)[grp == -1], n)
    b0, V0 = M.fit(y, Zo + [Zo_miss], offset=Z1)
    terms = []
    for g in range(3):
        terms += [Zc[g], Zo[g]]
    bf, Vf = M.fit(y, terms + [G.zsum(rows[grp == -1], Lf[grp == -1], n), Zo_miss], offset=Z1)
    for g in range(3):
        s0, se0 = -b0[g], float(np.sqrt(V0[g, g]))
        c, s = -bf[2 * g], -bf[2 * g + 1]
        Vcs = np.array([[Vf[2 * g, 2 * g], Vf[2 * g, 2 * g + 1]], [Vf[2 * g + 1, 2 * g], Vf[2 * g + 1, 2 * g + 1]]])
        g30, e30 = G.gap_ci(c, s, Vcs, 0.30)
        out.append(f"| {names[g]} | {int((grp == g).sum()):,} | {s0:.3f} [{s0 - 1.96 * se0:.3f}, {s0 + 1.96 * se0:.3f}] | {c:+.3f} | {s:.3f} | "
                   f"{g30:.3f} [{g30 - 1.96 * e30:.3f}, {g30 + 1.96 * e30:.3f}] |")
    out.append("")
    # bins by group
    edges = [0.0, 0.16, 0.20, 0.24, 0.28, 1.0]
    Zb, labs = [], []
    for g in range(3):
        for lo, hi in zip(edges[:-1], edges[1:]):
            m = (grp == g) & (Lab >= lo) & (Lab < hi)
            Zb.append(G.zsum(rows[m], Lf[m], n)); labs.append((g, lo, hi, int(m.sum()), float(Lab[m].mean()) if m.any() else 0.0))
    Zb.append(G.zsum(rows[grp == -1], Lf[grp == -1], n))
    bb, Vb = M.fit(y, Zb, offset=Z1)
    out.append("## 2. Share bins by playmaking group (gap, points per attempt; published PAC would charge 0.25 x mean L)\n")
    out.append("| share bin | pure scorers | middle | playmakers | published PAC 0.25 L |\n|---|---|---|---|---|")
    for j, (lo, hi) in enumerate(zip(edges[:-1], edges[1:])):
        cells = []
        for g in range(3):
            k = g * (len(edges) - 1) + j
            gg, se = -bb[k], float(np.sqrt(Vb[k, k]))
            cells.append(f"{gg:+.3f} [{gg - 1.96 * se:+.3f}, {gg + 1.96 * se:+.3f}] (n {labs[k][3]:,})")
        mL = np.mean([labs[g * (len(edges) - 1) + j][4] for g in range(3)])
        out.append(f"| {lo:.2f}-{hi:.2f} | " + " | ".join(cells) + f" | {0.25 * mL:.3f} |")
    txt = "\n".join(out)
    open(os.path.join(HERE, "_pac_scarcity_forms.md"), "w", encoding="utf-8").write(txt)
    print(txt)

if __name__ == "__main__":
    main()
