# -*- coding: utf-8 -*-
"""_pac_team_price.py -- can the replacement price be estimated per team instead of per league?

Base: the main model of _pac_gamelevel.py with the validated hinge schedule (gap = s_h max(0, L - L0)).
A team-specific additive shift delta_t (points per attempt; + = that team's replacements are worse than the league
schedule says) enters as  -delta_t * sum L_full  for the absences of team t. Estimated from the base model's residuals
(Frisch-Waugh on the absorbed absence load), one team-season or franchise at a time.

1. Team-season shifts: DerSimonian-Laird between-team variance (tau), I^2, split-half reliability (odd vs even team
   games), empirical-Bayes shrinkage, and whether shrunk first-half shifts improve second-half predictions.
2. Franchise shifts pooled over seasons, and year-over-year persistence of team-season shifts.
3. Roster-based price: does the gap depend on who is still playing? (another 25%+ creator present that night;
   number of present teammates at 20%+ share).
Writes _pac_team_price.md.
"""
import json
import os
import pickle
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _pac_gamelevel as G  # noqa: E402

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
HERE = os.path.dirname(os.path.abspath(__file__))


def dl(est, se):
    """DerSimonian-Laird random-effects: pooled mean, tau^2, I^2."""
    w = 1 / se ** 2
    mu = np.sum(w * est) / np.sum(w)
    Q = np.sum(w * (est - mu) ** 2)
    k = len(est)
    tau2 = max(0.0, (Q - (k - 1)) / (np.sum(w) - np.sum(w ** 2) / np.sum(w)))
    I2 = max(0.0, (Q - (k - 1)) / Q) if Q > 0 else 0.0
    return mu, tau2, I2, Q, k


def shifts(groups, r, e, w, mask=None):
    """per-group delta = sum(w r e)/sum(w r^2), robust SE; r = -(absorbed absence load)."""
    m = np.ones(len(e), bool) if mask is None else mask
    g = groups[m]
    num = np.bincount(g, weights=(w * r * e)[m], minlength=groups.max() + 1)
    den = np.bincount(g, weights=(w * r * r)[m], minlength=groups.max() + 1)
    ok = den > 0
    d = np.where(ok, num / np.where(ok, den, 1), np.nan)
    # robust SE: sum (w r e)^2 / den^2, using the residual net of the group's own shift
    e2 = e - np.where(ok, d, 0)[groups] * r
    meat = np.bincount(g, weights=((w * r * e2) ** 2)[m], minlength=groups.max() + 1)
    se = np.where(ok, np.sqrt(meat) / np.where(ok, den, 1), np.nan)
    return d, se, den


def main():
    with open(os.path.join(HERE, "_pac_gamelevel_results.json"), encoding="utf-8") as f:
        H = json.load(f)["hinge"]
    s_h, L0 = H["s_h"], H["L0"]
    A = G.assemble(ft_w=0.44, outcome="tsa", min_apps=10, min_den=4.0)
    tg, P, ev = A["tg"], A["P"], A["ev"]
    y, Z1, Z0 = A["y"], A["Z1"], A["Z0"]
    w = A["w"]
    n = len(y)
    ab_rows, ab_pl = ev["absent_rows"], ev["absent_pl"]
    Lab = P.L.values[ab_pl]
    Zh = G.zsum(ab_rows, P.L_full.values[ab_pl] * np.maximum(0.0, Lab - L0), n)
    M, _ = G.model_for(A)
    beta, V = M.fit(y, [Zh], offset=Z1)
    D = M.demean([y - Z1, Zh, Z0])
    X = np.column_stack([D[:, 1:2], M.Xd])
    e = D[:, 0] - X @ beta                      # residual of the league-schedule model
    r = -D[:, 2]                                # absorbed absence load; delta_t enters as -delta_t * sum L_full
    ts_lab = (tg.team.astype(str) + "_" + tg.season.astype(str)).values
    ts = pd.factorize(ts_lab)[0]
    fr = pd.factorize(tg.team.astype(str).values)[0]
    out = ["# Per-team replacement prices\n",
           f"Generated by `_pac_team_price.py`. League schedule: gap = {s_h:.3f} max(0, L - {L0:.2f}), s_h re-fit here = {-beta[0]:.3f}. "
           "delta = a team's shift in the gap, points per attempt (+ = its replacements are worse than the league schedule says; "
           "x50 for TS points). Estimated from the league model's residuals against the team's absorbed absence load.\n"]

    # ---------- 1. team-season
    d, se, den = shifts(ts, r, e, w)
    ok = np.isfinite(d) & np.isfinite(se) & (se > 0)
    mu, tau2, I2, Q, k = dl(d[ok], se[ok])
    tau = np.sqrt(tau2)
    rel = tau2 / (tau2 + se[ok] ** 2)
    out.append("## 1. Team-season shifts (863 team-seasons)\n")
    out.append(f"- median SE of one team-season's shift: **{np.median(se[ok]):.3f}** points per attempt ({50 * np.median(se[ok]):.1f} TS points)")
    out.append(f"- spread of raw estimates (SD): {np.std(d[ok]):.3f}; true between-team SD (tau, DerSimonian-Laird): **{tau:.3f}** "
               f"({50 * tau:.1f} TS points); I^2 = {100 * I2:.0f}% (share of the spread that is real, not noise)")
    out.append(f"- reliability of a single team-season estimate, tau^2/(tau^2+SE^2): median **{np.median(rel):.2f}**")
    # split-half
    par = (tg.k.values % 2 == 0)
    dA, seA, _ = shifts(ts, r, e, w, mask=par)
    dB, seB, _ = shifts(ts, r, e, w, mask=~par)
    okh = np.isfinite(dA) & np.isfinite(dB) & (seA > 0) & (seB > 0)
    wts = 1 / (seA[okh] ** 2 + seB[okh] ** 2)
    def wcorr(a, b, ww):
        ma, mb = np.average(a, weights=ww), np.average(b, weights=ww)
        return np.sum(ww * (a - ma) * (b - mb)) / np.sqrt(np.sum(ww * (a - ma) ** 2) * np.sum(ww * (b - mb) ** 2))
    out.append(f"- split-half (even vs odd team games): correlation of a team's two estimates **{np.corrcoef(dA[okh], dB[okh])[0, 1]:.3f}** "
               f"(precision-weighted {wcorr(dA[okh], dB[okh], wts):.3f}); a real team-specific price needs this well above 0")
    # out-of-sample: shrunk even-game shift predicting odd-game residuals
    muA, tau2A, _, _, _ = dl(dA[okh], seA[okh])
    shrinkA = np.zeros_like(dA)
    shrinkA[okh] = muA + tau2A / (tau2A + seA[okh] ** 2) * (dA[okh] - muA)
    te = ~par & okh[ts]
    base = np.sum(w[te] * e[te] ** 2)
    adj = np.sum(w[te] * (e[te] - shrinkA[ts[te]] * r[te]) ** 2)
    raw = np.sum(w[te] * (e[te] - np.where(okh, dA, 0)[ts[te]] * r[te]) ** 2)
    out.append(f"- predicting odd games from even-game shifts: weighted SSE change vs the league schedule: shrunk {100 * (adj / base - 1):+.3f}%, "
               f"unshrunk {100 * (raw / base - 1):+.3f}% (negative = team prices help)\n")
    # most extreme shrunk team-seasons
    shr = np.full_like(d, np.nan)
    shr[ok] = mu + tau2 / (tau2 + se[ok] ** 2) * (d[ok] - mu)
    names = pd.Series(ts_lab).groupby(ts).first().values
    order = np.argsort(np.where(ok, shr, np.nan))
    valid = [i for i in order if ok[i]]
    out.append("Shrunk team-season shifts, most extreme (points per attempt): cheapest replacements "
               + ", ".join(f"{names[i]} {shr[i]:+.3f}" for i in valid[:3]) + "; costliest "
               + ", ".join(f"{names[i]} {shr[i]:+.3f}" for i in valid[-3:]) + f". Range of shrunk shifts: [{np.nanmin(shr):+.3f}, {np.nanmax(shr):+.3f}].\n")

    # ---------- 2. franchise and persistence
    df_, sef, _ = shifts(fr, r, e, w)
    okf = np.isfinite(df_) & (sef > 0)
    muf, tau2f, I2f, Qf, kf = dl(df_[okf], sef[okf])
    out.append("## 2. Franchise shifts (all seasons pooled) and persistence\n")
    out.append(f"- median SE of a franchise's shift: {np.median(sef[okf]):.3f}; tau = **{np.sqrt(tau2f):.3f}** ({50 * np.sqrt(tau2f):.1f} TS points); I^2 = {100 * I2f:.0f}%")
    team_of = tg.team.values
    seas_of = tg.season.values
    info = pd.DataFrame({"ts": ts, "team": team_of, "season": seas_of}).drop_duplicates("ts").set_index("ts")
    tsd = pd.DataFrame({"d": d, "se": se}).join(info)
    tsd = tsd[np.isfinite(tsd.d) & (tsd.se > 0)]
    nxt = tsd.copy(); nxt["season"] -= 1
    yy = tsd.merge(nxt[["team", "season", "d"]], on=["team", "season"], suffixes=("", "_next"))
    out.append(f"- year-over-year correlation of a team's shift (same franchise, next season): **{np.corrcoef(yy.d, yy.d_next)[0, 1]:.3f}** (n = {len(yy)})\n")

    # ---------- 3. roster-based price: who is still playing?
    L_of = {}
    for rr in P.itertuples(index=False):
        L_of[(int(rr.pid), int(rr.team), int(rr.season))] = rr.L
    maxL, n20 = np.zeros(n), np.zeros(n)
    for y_ in G.YEARS:
        with open(os.path.join(HERE, f"_pacgl_season_{G.code_of(y_)}.pkl"), "rb") as f:
            pg = pickle.load(f)["pg"][["gid", "pid", "team"]]
        pg = pg.assign(L=[L_of.get((int(p), int(t), y_), np.nan) for p, t in zip(pg.pid, pg.team)]).dropna(subset=["L"])
        agg = pg.groupby(["gid", "team"]).L.agg(maxL="max", n20=lambda s: int((s >= 0.20).sum()))
        idx = [(g, t) for g, t in zip(tg.gid.values, tg.team.values)]
        sel = tg.season.values == y_
        ai = agg.reindex([idx[i] for i in np.where(sel)[0]])
        maxL[sel] = ai["maxL"].fillna(0).values
        n20[sel] = ai["n20"].fillna(0).values
    Lf = P.L_full.values[ab_pl]
    other = maxL[ab_rows]                       # highest share among teammates who played that night
    oc = (other >= 0.25).astype(float)
    dep = n20[ab_rows]
    Z_oc = G.zsum(ab_rows, Lf * oc, n)
    Z_ocL = G.zsum(ab_rows, Lf * oc * np.maximum(0.0, Lab - L0), n)
    Z_dep = G.zsum(ab_rows, Lf * (dep - dep.mean()), n)
    b1, V1 = M.fit(y, [Zh, Z_oc], offset=Z1)
    b2, V2 = M.fit(y, [Zh, Z_oc, Z_ocL], offset=Z1)
    b3, V3 = M.fit(y, [Zh, Z_dep], offset=Z1)
    ci = lambda b, s: f"{b:+.3f} [{b - 1.96 * s:+.3f}, {b + 1.96 * s:+.3f}]"
    out.append("## 3. Roster-based price: does the gap depend on who is still playing?\n")
    out.append(f"- absences where another 25%+ creator played that night: {int(oc.sum()):,} of {len(oc):,} ({100 * oc.mean():.0f}%)")
    out.append(f"- gap shift when another 25%+ creator plays (points per attempt): **{ci(-b1[1], np.sqrt(V1[1, 1]))}**")
    out.append(f"- same, allowing the slope to change: level {ci(-b2[1], np.sqrt(V2[1, 1]))}, slope above threshold {ci(-b2[2], np.sqrt(V2[2, 2]))} "
               f"(league slope {-b2[0]:.3f})")
    out.append(f"- gap shift per extra present teammate at 20%+ share: **{ci(-b3[1], np.sqrt(V3[1, 1]))}**")
    txt = "\n".join(out)
    with open(os.path.join(HERE, "_pac_team_price.md"), "w", encoding="utf-8") as f:
        f.write(txt)
    print(txt)


if __name__ == "__main__":
    main()
