# -*- coding: utf-8 -*-
"""_pac_vs_tsadd.py -- head to head: PAC vs TS Add (UW-rTS = TS Add / 100) against what teams actually lose.

1. Calibration by share: team points per game on the number of absent rotation players in each share bin, with the main
   model's fixed effects (roster spell, opponent-season, season-month) and controls. The coefficient is what a team actually
   loses per game when a player in that bin sits. Compared with the absent players' own TS Add/g and PAC/g.
2. Year-over-year stability of PPG, TS Add/g and PAC/g (players qualified in consecutive seasons).
Writes _pac_vs_tsadd.md.
"""
import json
import os
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _pac_gamelevel as G  # noqa: E402

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
HERE = os.path.dirname(os.path.abspath(__file__))
EDGES = [0.0, 0.15, 0.20, 0.25, 0.30, 1.0]


def main():
    with open(os.path.join(HERE, "_pac_gamelevel_results.json"), encoding="utf-8") as f:
        H = json.load(f)["hinge"]
    s_h, L0 = H["s_h"], H["L0"]
    vals = []
    for y in G.YEARS:
        with open(os.path.join(HERE, f"_sv_season_{G.code_of(y)}.json"), encoding="utf-8") as f:
            S = pd.DataFrame(json.load(f)["rows"])[["pid", "name", "gp", "poss", "pts", "tsa", "tsadd", "l"]]
        S["season"] = y
        vals.append(S)
    V = pd.concat(vals, ignore_index=True)
    V["pid"] = V.pid.astype("int64")
    V["ppg"] = V.pts / V.gp
    V["tsaddg"] = V.tsadd / V.gp
    V["pubg"] = (V.tsadd + V.tsa * 0.25 * V.l.fillna(0)) / V.gp
    V["valg"] = (V.tsadd + V.tsa * s_h * np.maximum(0.0, V.l.fillna(0) - L0)) / V.gp

    A = G.assemble(ft_w=0.44, outcome="tsa", min_apps=10, min_den=4.0)
    tg, P, ev = A["tg"], A["P"], A["ev"]
    n = len(tg)
    Pm = P[["pid", "season"]].copy()
    Pm["pid"] = Pm.pid.astype("int64")
    Pm = Pm.merge(V[["pid", "season", "ppg", "tsaddg", "pubg", "valg"]], on=["pid", "season"], how="left")
    rows, pl = ev["absent_rows"], ev["absent_pl"]
    Lab = P.L.values[pl]
    counts, labs = [], []
    for lo, hi in zip(EDGES[:-1], EDGES[1:]):
        m = (Lab >= lo) & (Lab < hi)
        counts.append(np.bincount(rows[m], minlength=n).astype(float))
        sub = Pm.iloc[pl[m]]
        labs.append(dict(lo=lo, hi=hi, n=int(m.sum()), ppg=float(sub.ppg.mean()), tsadd=float(sub.tsaddg.mean()),
                         pub=float(sub.pubg.mean()), val=float(sub.valg.mean())))
    M, _ = G.model_for(A)
    b, Vb = M.fit(tg.pts.values.astype(float), counts)
    out = ["# PAC vs TS Add (UW-rTS = TS Add / 100), head to head\n",
           "Generated by `_pac_vs_tsadd.py`.\n",
           "## 1. What teams actually lose when a player sits, vs what each stat says he is worth (points per game)\n",
           "Actual = coefficient on the number of absent rotation players in the share bin, team points per game, with roster-spell, "
           "opponent-season and season-month fixed effects plus home/rest/opponent-absence controls (95% CI, clustered by team-season).\n",
           "| absent player's share | absences | his PPG | **actually lost** | TS Add/g says | PAC/g (published) says | PAC/g (validated) says |",
           "|---|---|---|---|---|---|---|"]
    err = {"tsadd": [], "pub": [], "val": []}
    wts = []
    for j, r in enumerate(labs):
        act, se = -b[j], float(np.sqrt(Vb[j, j]))
        out.append(f"| {r['lo']:.0%}-{r['hi']:.0%} | {r['n']:,} | {r['ppg']:.1f} | **{act:.2f}** [{act - 1.96 * se:.2f}, {act + 1.96 * se:.2f}] | "
                   f"{r['tsadd']:.2f} | {r['pub']:.2f} | {r['val']:.2f} |")
        for k in err:
            err[k].append(r[k] - act)
        wts.append(r["n"])
    wts = np.array(wts, float)
    out.append("")
    out.append("Absence-weighted mean absolute error vs what is actually lost: " + ", ".join(
        f"{lab} {np.average(np.abs(err[k]), weights=wts):.2f}" for k, lab in (("tsadd", "TS Add"), ("pub", "PAC published"), ("val", "PAC validated")))
        + " points per game. Error at 30%+ share: " + ", ".join(
        f"{lab} {err[k][-1]:+.2f}" for k, lab in (("tsadd", "TS Add"), ("pub", "PAC published"), ("val", "PAC validated"))) + ".\n")

    # 2. stability
    q = V[(V.gp >= 40) & (V.poss >= 2500)].copy()
    nx = q.copy(); nx["season"] -= 1
    yy = q.merge(nx[["pid", "season", "ppg", "tsaddg", "valg"]], on=["pid", "season"], suffixes=("", "_n"))
    out.append("## 2. Year-over-year stability (qualified in consecutive seasons, n = %d)\n" % len(yy))
    out.append("| stat | correlation with next season |\n|---|---|")
    for c, lab in (("ppg", "PPG"), ("tsaddg", "TS Add/g (= UW-rTS x 100)"), ("valg", "PAC/g (validated)")):
        out.append(f"| {lab} | {yy[c].corr(yy[c + '_n']):.3f} |")
    txt = "\n".join(out)
    with open(os.path.join(HERE, "_pac_vs_tsadd.md"), "w", encoding="utf-8") as f:
        f.write(txt)
    print(txt)


if __name__ == "__main__":
    main()
