# -*- coding: utf-8 -*-
"""_pac_replacement_examples.py -- what a measured replacement level for scoring lets you compute.

Validated PAC = TS Add + TSA * s_h * max(0, L - L0): points of team scoring above what the possessions return
without him. TS Add = the same quantity under the league-average assumption.
Wins use the rule of thumb of ~2.7 wins per point of per-game margin over 82 games (~30.4 points per win);
it is an illustration, not an estimate from this paper. Writes _pac_replacement_examples.md.
"""
import json
import os
import sys

import numpy as np
import pandas as pd

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
HERE = os.path.dirname(os.path.abspath(__file__))
PTS_PER_WIN = 82 / 2.7
SEASON_GAMES = {1998: 50, 2011: 66, 2019: 72, 2020: 72}   # start years with short seasons (2019-20 varied; 72 used)


def lab(y):
    return f"{y % 100:02d}-{(y + 1) % 100:02d}"


def main():
    with open(os.path.join(HERE, "_pac_gamelevel_results.json"), encoding="utf-8") as f:
        h = json.load(f)["hinge"]
    s_h, L0 = h["s_h"], h["L0"]
    rows = []
    for y in range(1997, 2026):
        code = f"{y % 100:02d}{(y + 1) % 100:02d}"
        with open(os.path.join(HERE, f"_sv_season_{code}.json"), encoding="utf-8") as f:
            for r in json.load(f)["rows"]:
                r = dict(r); r["season"] = y; rows.append(r)
    S = pd.DataFrame(rows)
    S["pac_v"] = S.tsadd + S.tsa * s_h * np.maximum(0.0, S.l.fillna(0) - L0)
    S["w_v"] = S.pac_v
    S["w_la"] = S.tsadd
    S["ppg"] = S.pts / S.gp
    q = S[(S.gp >= 40) & (S.poss >= 2500)].copy()
    out = ["# PAC examples\n",
           f"Generated by `_pac_replacement_examples.py`. Validated schedule gap = {s_h:.3f} max(0, L - {L0:.2f}). "
           "All values are PAC points (season or career totals); TS Add is the same quantity at a league-average price.\n"]

    # A. league-average efficiency, real value
    avg = q[(q.rts.abs() <= 1.0)].sort_values("pac_v", ascending=False).head(10)
    out.append("## A. Scorers at league-average efficiency (rTS within +/-1): worth ~0 by TS Add\n")
    out.append("| season | share | rTS | PPG | TS Add (pts) | PAC (pts) |\n|---|---|---|---|---|---|")
    for _, r in avg.iterrows():
        out.append(f"| {r['name']} {lab(r.season)} | {r.l:.0%} | {r.rts:+.1f} | {r.ppg:.1f} | {r.w_la:+.0f} | **{r.w_v:+.0f}** |")
    out.append("")

    # B. 2025-26: scoring wins above replacement and what the missed games cost
    cur = q[q.season == 2025].sort_values("pac_v", ascending=False).head(12).copy()
    cur["missed"] = (82 - cur.gp).clip(lower=0)
    cur["miss_cost"] = cur.missed * cur.pac_v / cur.gp
    out.append("## B. 2025-26: season PAC, and the PAC his missed games cost\n")
    out.append("| player | GP | TS Add (pts) | PAC (pts) | games missed | PAC lost to missed games (pts) |\n|---|---|---|---|---|---|")
    for _, r in cur.iterrows():
        out.append(f"| {r['name']} | {int(r.gp)} | {r.w_la:+.0f} | **{r.w_v:+.0f}** | {int(r.missed)} | {r.miss_cost:.0f} |")
    out.append("")

    # C. all-time single seasons
    top = q.sort_values("pac_v", ascending=False).head(10)
    q["rk_la_all"] = q.tsadd.rank(ascending=False, method="min").astype(int)
    out.append("## C. Best single PAC seasons, 1997-98 to 2025-26\n")
    out.append("| season | share | rTS | PAC (pts) | TS Add (pts, all-time rank) |\n|---|---|---|---|---|")
    for i, r in top.iterrows():
        out.append(f"| {r['name']} {lab(r.season)} | {r.l:.0%} | {r.rts:+.1f} | **{r.w_v:.0f}** | {r.w_la:.0f} ({q.loc[i, 'rk_la_all']}) |")
    out.append("")

    # D. careers inside the sample window (all seasons, not only qualified)
    car = S.groupby("pid").agg(name=("name", "last"), seasons=("season", "nunique"), first=("season", "min"), last=("season", "max"),
                               w_v=("w_v", "sum"), w_la=("w_la", "sum")).sort_values("w_v", ascending=False)
    car["rk_la"] = car.w_la.rank(ascending=False, method="min").astype(int)
    out.append("## D. Career PAC (seasons 1997-98 to 2025-26 only)\n")
    out.append("| player | seasons in window | PAC (pts) | TS Add (pts, rank) |\n|---|---|---|---|")
    for _, r in car.head(12).iterrows():
        out.append(f"| {r['name']} | {lab(int(r['first']))} to {lab(int(r['last']))} ({int(r.seasons)}) | **{r.w_v:.0f}** | {r.w_la:.0f} ({r.rk_la}) |")
    out.append("")
    vol = car[(car.w_la < 150) & (car.seasons >= 8)].sort_values("w_v", ascending=False).head(8)
    out.append("## E. Careers TS Add calls nearly worthless (TS Add under 150 points, 8+ seasons)\n")
    out.append("| player | seasons | TS Add (pts) | PAC (pts) |\n|---|---|---|---|")
    for _, r in vol.iterrows():
        out.append(f"| {r['name']} | {lab(int(r['first']))} to {lab(int(r['last']))} | {r.w_la:+.0f} | **{r.w_v:+.0f}** |")
    txt = "\n".join(out)
    with open(os.path.join(HERE, "_pac_replacement_examples.md"), "w", encoding="utf-8") as f:
        f.write(txt)
    print(txt)


if __name__ == "__main__":
    main()
