# -*- coding: utf-8 -*-
"""_pac_cases_025.py -- headline cases for the PAC working paper, all at the published price s = 0.25.

Reads _sv_season_*.json (built by _sv_pergame.py at SLOPE = 0.25; fields tsadd, credit = 0.25*TSA*L, pac).
Qualified pool: >= 40 games and >= 2,500 on-court possessions (same pool as _pac_cases.py).
Per-game values; ranks within season. Writes _pac_cases_025.md.
"""
import json
import os
import sys

import numpy as np
import pandas as pd

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
HERE = os.path.dirname(os.path.abspath(__file__))

MVPS = [(1997, "Michael Jordan"), (1998, "Karl Malone"), (1999, "Shaquille"), (2000, "Allen Iverson"), (2001, "Tim Duncan"),
        (2002, "Tim Duncan"), (2003, "Kevin Garnett"), (2004, "Steve Nash"), (2005, "Steve Nash"), (2006, "Dirk Nowitzki"),
        (2007, "Kobe Bryant"), (2008, "LeBron James"), (2009, "LeBron James"), (2010, "Derrick Rose"), (2011, "LeBron James"),
        (2012, "LeBron James"), (2013, "Kevin Durant"), (2014, "Stephen Curry"), (2015, "Stephen Curry"),
        (2016, "Russell Westbrook"), (2017, "James Harden"), (2018, "Giannis"), (2019, "Giannis"), (2020, "Nikola Jok"),
        (2021, "Nikola Jok"), (2022, "Joel Embiid"), (2023, "Nikola Jok"), (2024, "Shai Gilgeous")]

NAMED = ["Allen Iverson", "Jalen Brunson", "Jaylen Brown", "Kobe Bryant", "Russell Westbrook", "DeMar DeRozan",
         "Carmelo Anthony", "Michael Jordan", "James Harden", "Zach LaVine", "Devin Booker", "Donovan Mitchell",
         "Anthony Edwards", "Jayson Tatum", "LaMelo Ball", "Tracy McGrady", "Vince Carter", "Paul Pierce",
         "Bradley Beal", "Kyrie Irving", "Damian Lillard", "Trae Young", "Ja Morant", "De'Aaron Fox"]


def lab(y):
    return f"{y % 100:02d}-{(y + 1) % 100:02d}"


def main():
    rows, lg = [], {}
    for y in range(1997, 2026):
        code = f"{y % 100:02d}{(y + 1) % 100:02d}"
        with open(os.path.join(HERE, f"_sv_season_{code}.json"), encoding="utf-8") as f:
            d = json.load(f)
        assert abs(d["summary"]["slope"] - 0.25) < 1e-9, code
        lg[y] = d["summary"]["lg_ts"]
        for r in d["rows"]:
            r = dict(r); r["season"] = y; rows.append(r)
    S = pd.DataFrame(rows)
    # identity check: pac = tsadd + 0.25 * tsa * l
    chk = (S.pac - (S.tsadd + 0.25 * S.tsa * S.l)).abs()
    q = S[(S.gp >= 40) & (S.poss >= 2500)].copy()
    q["ppg"] = q.pts / q.gp
    q["tsaddg"] = q.tsadd / q.gp
    q["pacg"] = q.pac / q.gp
    for c in ("ppg", "tsaddg", "pacg"):
        q[f"rk_{c}"] = q.groupby("season")[c].rank(ascending=False, method="min").astype(int)
    q["n"] = q.groupby("season").pid.transform("size")

    out = ["# PAC cases at s = 0.25 (published price)\n",
           f"Generated by `_pac_cases_025.py`. Pool: {len(q):,} qualified player-seasons (>= 40 games, >= 2,500 possessions), "
           "1997-98 to 2025-26. Per-game values, ranks within season. "
           f"Identity check |pac - (tsadd + 0.25 TSA L)|: max {chk.max():.2f} points (rounding).\n"]

    # 1. heavy-usage seasons
    hi = q[q.l >= 0.30]
    neg_ts = hi[hi.tsadd < 0]
    neg_pac = hi[hi.pac < 0]
    flip = hi[(hi.tsadd < 0) & (hi.pac > 0)]
    out.append("## 1. Seasons at >= 30% share\n")
    out.append(f"- seasons: {len(hi)}")
    out.append(f"- TS Points Added below zero (below league average): **{len(neg_ts)}**")
    out.append(f"- PAC below zero (below break-even): **{len(neg_pac)}**: "
               + ", ".join(f"{r['name']} {lab(r.season)}" for _, r in neg_pac.iterrows()))
    out.append(f"- negative by TS Points Added, positive by PAC: **{len(flip)}**\n")

    # 2. scoring champions
    champs = q[q.rk_ppg == 1].sort_values("season")
    out.append("## 2. Scoring champions (PPG leader of each qualified pool)\n")
    out.append(f"- {len(champs)} seasons; TS Points Added below zero: **{int((champs.tsadd < 0).sum())}**; "
               f"PAC below zero: **{int((champs.pac < 0).sum())}**")
    out.append(f"- median rank: TS Points Added/g {int(champs.rk_tsaddg.median())}, PAC/g {int(champs.rk_pacg.median())}; "
               f"in the top 10: TS Points Added {int((champs.rk_tsaddg <= 10).sum())}, PAC {int((champs.rk_pacg <= 10).sum())}\n")
    out.append("| season | player | share | rTS | TS Add/g | rank | PAC/g | rank | of |\n|---|---|---|---|---|---|---|---|---|")
    for _, r in champs.iterrows():
        out.append(f"| {lab(r.season)} | {r['name']} | {r.l:.3f} | {r.rts:+.1f} | {r.tsaddg:+.2f} | {r.rk_tsaddg} | {r.pacg:+.2f} | {r.rk_pacg} | {r.n} |")
    out.append("")

    # 3. MVPs
    out.append("## 3. MVPs (scoring only)\n")
    out.append("| season | player | share | rTS | PPG rk | TS Add/g | rank | PAC/g | rank | of |\n|---|---|---|---|---|---|---|---|---|---|")
    for y, nm in MVPS:
        m = q[(q.season == y) & q.name.str.contains(nm, regex=False)]
        if len(m) != 1:
            out.append(f"| {lab(y)} | {nm} | (not found: {len(m)}) |"); continue
        r = m.iloc[0]
        out.append(f"| {lab(y)} | {r['name']} | {r.l:.3f} | {r.rts:+.1f} | {r.rk_ppg} | {r.tsaddg:+.2f} | {r.rk_tsaddg} | {r.pacg:+.2f} | {r.rk_pacg} | {r.n} |")
    out.append("")

    # 4. named players, every qualified season
    out.append("## 4. Named players, every qualified season\n")
    out.append("| player | season | share | rTS | PPG (rk) | TS Add/g (rk) | PAC/g (rk) | of |\n|---|---|---|---|---|---|---|---|")
    for nm in NAMED:
        m = q[q.name == nm].sort_values("season")
        for _, r in m.iterrows():
            out.append(f"| {nm} | {lab(r.season)} | {r.l:.3f} | {r.rts:+.1f} | {r.ppg:.1f} ({r.rk_ppg}) | {r.tsaddg:+.2f} ({r.rk_tsaddg}) | "
                       f"{r.pacg:+.2f} ({r.rk_pacg}) | {r.n} |")
    out.append("")

    # 5. careers (all games, not only qualified seasons)
    out.append("## 5. Career totals, all seasons in the files (points)\n")
    out.append("| player | seasons | TS Points Added | PAC | PTS |\n|---|---|---|---|---|")
    for nm in NAMED:
        m = S[S.name == nm]
        if len(m):
            out.append(f"| {nm} | {len(m)} | {m.tsadd.sum():+,.0f} | {m.pac.sum():+,.0f} | {m.pts.sum():,.0f} |")
    out.append("")

    # 6. biggest flips among top-5 scorers
    top = q[(q.rk_ppg <= 5) & (q.tsadd < 0)].sort_values("pacg", ascending=False)
    out.append("## 6. Top-5 scorers with negative TS Points Added (sorted by PAC/g)\n")
    out.append(f"{len(top)} seasons.\n")
    out.append("| season | player | share | rTS | PPG rk | TS Add/g (rk) | PAC/g (rk) | of |\n|---|---|---|---|---|---|---|---|")
    for _, r in top.iterrows():
        out.append(f"| {lab(r.season)} | {r['name']} | {r.l:.3f} | {r.rts:+.1f} | {r.rk_ppg} | {r.tsaddg:+.2f} ({r.rk_tsaddg}) | {r.pacg:+.2f} ({r.rk_pacg}) | {r.n} |")
    out.append("")

    with open(os.path.join(HERE, "_pac_cases_025.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
