# -*- coding: utf-8 -*-
"""_pac_how_sure.py -- how close is the estimate to the true price?

1. Known-answer test (semi-synthetic). Keep the real games, fixed effects, controls, absence patterns and residual
   noise; remove the estimated absence effect and plant a known price instead; re-run the estimator. Residuals are
   reshuffled within team-season for each replicate. If the method is sound it recovers every planted price,
   including "no effect" and "no threshold".
2. Hidden-confounder sensitivity (Cinelli & Hazlett 2020 robustness value): how much of the leftover variation in both
   team efficiency and absence load an unmeasured factor would have to explain to erase the estimate, benchmarked
   against the strongest measured confounder (back-to-backs).
Writes _pac_how_sure.md.
"""
import json
import os
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _pac_gamelevel as G  # noqa: E402

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
HERE = os.path.dirname(os.path.abspath(__file__))
L0_GRID = [0.0, 0.04, 0.06, 0.08, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.20, 0.22]
REPS = 40


def main():
    with open(os.path.join(HERE, "_pac_gamelevel_results.json"), encoding="utf-8") as f:
        H = json.load(f)["hinge"]
    A = G.assemble(ft_w=0.44, outcome="tsa", min_apps=10, min_den=4.0)
    tg, P, ev = A["tg"], A["P"], A["ev"]
    y, Z1, Z0, Z2, w = A["y"], A["Z1"], A["Z0"], A["Z2"], A["w"]
    n = len(y)
    rows, pl = ev["absent_rows"], ev["absent_pl"]
    Lf, Lab = P.L_full.values[pl], P.L.values[pl]
    Zh = {L0: G.zsum(rows, Lf * np.maximum(0.0, Lab - L0), n) for L0 in L0_GRID}
    M, _ = G.model_for(A)
    Xd = M.Xd
    # demean once: every absence column
    cols = [Z1, Z0, Z2] + [Zh[L0] for L0 in L0_GRID]
    D = M.demean(cols)
    Z1d, Z0d, Z2d = D[:, 0], D[:, 1], D[:, 2]
    Zhd = {L0: D[:, 3 + j] for j, L0 in enumerate(L0_GRID)}
    sw = np.sqrt(w)

    def ols(yd, Zc):
        X = np.column_stack(Zc + [Xd])
        b = np.linalg.lstsq(X * sw[:, None], yd * sw, rcond=None)[0]
        return b, float(np.sum(w * (yd - X @ b) ** 2))

    # fitted real model (hinge at the estimated threshold) -> control effects and residual noise
    L0_hat = H["L0"]
    yd_real = M.demean([y])[:, 0]
    b_real, _ = ols(yd_real - Z1d, [Zhd[L0_hat]])
    s_hat = -b_real[0]
    e = (yd_real - Z1d) - np.column_stack([Zhd[L0_hat], Xd]) @ b_real
    ctrl = Xd @ b_real[1:]
    ts = pd.factorize(tg.team.astype(str) + "_" + tg.season.astype(str))[0]
    order = np.argsort(ts, kind="stable")
    bounds = np.searchsorted(ts[order], np.arange(ts.max() + 2))

    def estimate(yd):
        yo = yd - Z1d
        prof = [(L0, *ols(yo, [Zhd[L0]])) for L0 in L0_GRID]
        L0s, bs, ssr = min(prof, key=lambda t: t[2])
        b0, _ = ols(yo, [Zhd[0.0]])
        bf, _ = ols(yo, [Z0d, Z2d])
        return dict(L0=L0s, s_h=-bs[0], s_origin=-b0[0], c=-bf[0], s=-bf[1], gap30=-bf[0] - 0.30 * bf[1])

    truths = [
        ("no effect (league-average replacement)", 0.0, 0.0),
        ("no threshold: gap = 0.25 L (PAC as published)", 0.25, 0.0),
        (f"the estimate: gap = {s_hat:.3f} max(0, L - {L0_hat:.2f})", s_hat, L0_hat),
        ("steeper, later threshold: gap = 0.80 max(0, L - 0.18)", 0.80, 0.18),
    ]
    rng = np.random.default_rng(3)
    out = ["# How close is the estimate to the true price?\n", "Generated by `_pac_how_sure.py`.\n",
           "## 1. Known-answer test\n",
           f"Real games, fixed effects, controls, absence patterns and residual noise; the estimated absence effect is removed "
           f"and a known price planted; residuals reshuffled within team-season, {REPS} replicates per planted price.\n",
           "| planted price | true gap at L = 0.30 | recovered threshold (mean, SD) | recovered slope (mean, SD) | recovered gap at L = 0.30 (mean, SD) | through-origin s (mean) |",
           "|---|---|---|---|---|---|"]
    for lab, s_true, L0_true in truths:
        truth_d = Z1d - s_true * (Zhd[L0_true] if L0_true in Zhd else M.demean([G.zsum(rows, Lf * np.maximum(0.0, Lab - L0_true), n)])[:, 0])
        res = []
        for _ in range(REPS):
            perm = e.copy()
            for k in range(ts.max() + 1):
                idx = order[bounds[k]:bounds[k + 1]]
                perm[idx] = e[rng.permutation(idx)]
            perm_d = M.demean([perm])[:, 0]
            res.append(estimate(ctrl + perm_d + truth_d))
        R = pd.DataFrame(res)
        g30 = s_true * max(0.0, 0.30 - L0_true)
        out.append(f"| {lab} | {g30:.3f} | {R.L0.mean():.3f} ({R.L0.std():.3f}) | {R.s_h.mean():.3f} ({R.s_h.std():.3f}) | "
                   f"{R.gap30.mean():.3f} ({R.gap30.std():.3f}) | {R.s_origin.mean():.3f} |")
        print(lab, "done", flush=True)
    out.append("")

    # ---------- 2. robustness value
    b, V = M.fit(y, [Zh[L0_hat]], offset=Z1)
    t = -b[0] / np.sqrt(V[0, 0])
    n_fe = sum(len(np.unique(A["G"][f])) for f in G.MAIN_FE)
    dof = n - n_fe - (1 + Xd.shape[1])
    f2 = t ** 2 / dof
    rv = 0.5 * (np.sqrt(f2 ** 2 + 4 * f2) - f2)
    r2_yd = t ** 2 / (t ** 2 + dof)
    # benchmark: own back-to-back (the most plausible confounder of absences)
    j_b2b = A["xnames"].index("rest_b2b")
    t_b2b_y = b[1 + j_b2b] / np.sqrt(V[1 + j_b2b, 1 + j_b2b])
    r2_b2b_y = t_b2b_y ** 2 / (t_b2b_y ** 2 + dof)
    # partial R2 of b2b with the absence term, given the other controls and fixed effects
    others = [k for k in range(Xd.shape[1]) if k != j_b2b]
    Xo = Xd[:, others]
    def resid(v):
        bb = np.linalg.lstsq(Xo * sw[:, None], v * sw, rcond=None)[0]
        return v - Xo @ bb
    zr, br = resid(Zhd[L0_hat]), resid(Xd[:, j_b2b])
    r2_b2b_d = float(np.sum(w * zr * br) ** 2 / (np.sum(w * zr ** 2) * np.sum(w * br ** 2)))
    out.append("## 2. Hidden-confounder sensitivity (robustness value)\n")
    out.append(f"- t-statistic of the slope (cluster-robust): {t:.1f}; residual degrees of freedom {dof:,}")
    out.append(f"- partial R^2 of the absence term with team efficiency: {100 * r2_yd:.2f}%")
    out.append(f"- **robustness value: {100 * rv:.1f}%**. An unmeasured factor would have to explain at least {100 * rv:.1f}% of the leftover "
               "variation in BOTH team efficiency and absence load (after fixed effects and controls) to reduce the slope to zero.")
    out.append(f"- benchmark, own back-to-back: explains {100 * r2_b2b_y:.3f}% of leftover team efficiency and {100 * r2_b2b_d:.3f}% of leftover "
               f"absence load. A hidden factor would have to be about **{rv / max(r2_b2b_y, 1e-9):.0f}x** stronger than back-to-backs on the outcome side "
               f"and **{rv / max(r2_b2b_d, 1e-9):.0f}x** stronger on the absence side.")
    txt = "\n".join(out)
    with open(os.path.join(HERE, "_pac_how_sure.md"), "w", encoding="utf-8") as f:
        f.write(txt)
    print(txt)


if __name__ == "__main__":
    main()
