# -*- coding: utf-8 -*-
"""_pac_examples.py -- illustrative numbers for the write-up, all derived from the validated price schedule.

PAC(validated) = TS Add + TSA * s_h * max(0, L - L0), per game; TS Add = the league-average-replacement version.
Pool: >= 40 games, >= 2,500 possessions (6,315 player-seasons). Writes _pac_examples.md.
"""
import json
import os
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
HERE = os.path.dirname(os.path.abspath(__file__))

MVPS = [(1997, "Michael Jordan"), (1998, "Karl Malone"), (1999, "Shaquille"), (2000, "Allen Iverson"), (2001, "Tim Duncan"),
        (2002, "Tim Duncan"), (2003, "Kevin Garnett"), (2004, "Steve Nash"), (2005, "Steve Nash"), (2006, "Dirk Nowitzki"),
        (2007, "Kobe Bryant"), (2008, "LeBron James"), (2009, "LeBron James"), (2010, "Derrick Rose"), (2011, "LeBron James"),
        (2012, "LeBron James"), (2013, "Kevin Durant"), (2014, "Stephen Curry"), (2015, "Stephen Curry"),
        (2016, "Russell Westbrook"), (2017, "James Harden"), (2018, "Giannis"), (2019, "Giannis"), (2020, "Nikola Jok"),
        (2021, "Nikola Jok"), (2022, "Joel Embiid"), (2023, "Nikola Jok"), (2024, "Shai Gilgeous")]


def lab(y):
    return f"{y % 100:02d}-{(y + 1) % 100:02d}"


def main():
    with open(os.path.join(HERE, "_pac_gamelevel_results.json"), encoding="utf-8") as f:
        res = json.load(f)
    s_h, L0 = res["hinge"]["s_h"], res["hinge"]["L0"]
    rows = []
    for y in range(1997, 2026):
        code = f"{y % 100:02d}{(y + 1) % 100:02d}"
        with open(os.path.join(HERE, f"_sv_season_{code}.json"), encoding="utf-8") as f:
            for r in json.load(f)["rows"]:
                r = dict(r); r["season"] = y; rows.append(r)
    S = pd.DataFrame(rows)
    q = S[(S.gp >= 40) & (S.poss >= 2500)].copy()
    q["ppg"] = q.pts / q.gp
    q["tsaddg"] = q.tsadd / q.gp
    q["pacg"] = (q.tsadd + q.tsa * s_h * np.maximum(0.0, q.l - L0)) / q.gp
    q["pubg"] = (q.tsadd + q.tsa * 0.25 * q.l) / q.gp
    q["loadg"] = q.pacg - q.tsaddg
    for c in ("ppg", "tsaddg", "pacg", "pubg"):
        q[f"rk_{c}"] = q.groupby("season")[c].rank(ascending=False, method="min").astype(int)
    q["n"] = q.groupby("season").pid.transform("size")
    out = ["# Examples for the write-up\n", f"Generated by `_pac_examples.py`. Validated schedule gap = {s_h:.3f} max(0, L - {L0:.2f}). "
           f"Pool: {len(q):,} qualified player-seasons 1997-98 to 2025-26. Ranks per game within season.\n"]

    # 1. the heaviest-usage seasons: how many does league-average math call below average?
    hi = q[q.l >= 0.30]
    out.append("## 1. The heaviest-usage seasons (share >= 30%)\n")
    out.append(f"- {len(hi)} seasons. TS Add (league-average replacement) calls **{int((hi.tsadd < 0).sum())}** of them below average.")
    out.append(f"- Validated PAC calls **{int((hi.pacg < 0).sum())}** of them below break-even: "
               + ", ".join(f"{r['name']} {lab(r.season)}" for _, r in hi[hi.pacg < 0].iterrows()) + ".")
    flip = hi[(hi.tsadd < 0) & (hi.pacg > 0)]
    out.append(f"- **{len(flip)}** flip sign (negative TS Add, positive PAC), including "
               + ", ".join(f"{r['name']} {lab(r.season)}" for _, r in flip.sort_values('ppg', ascending=False).head(10).iterrows()) + ".\n")

    # 2. scoring champions and MVPs
    champs = q.loc[q.groupby("season").ppg.idxmax()]
    out.append("## 2. Scoring champions (PPG leader of each qualified pool)\n")
    out.append(f"- median rank by TS Add/g: **{int(champs.rk_tsaddg.median())}**; by validated PAC/g: **{int(champs.rk_pacg.median())}**")
    out.append(f"- in the top 10: TS Add/g {int((champs.rk_tsaddg <= 10).sum())} of {len(champs)}; validated PAC/g {int((champs.rk_pacg <= 10).sum())} of {len(champs)}\n")
    mv = []
    for y, nm in MVPS:
        r = q[(q.season == y) & (q.name.str.contains(nm))]
        if len(r):
            mv.append(r.iloc[0])
    M = pd.DataFrame(mv)
    out.append("## 3. MVPs (scoring rank only; MVP voting also rewards passing and defense)\n")
    out.append(f"- median rank: PPG {int(M.rk_ppg.median())}, TS Add/g {int(M.rk_tsaddg.median())}, published PAC/g {int(M.rk_pubg.median())}, validated PAC/g **{int(M.rk_pacg.median())}**")
    out.append(f"- in their season's top 5: PPG {int((M.rk_ppg <= 5).sum())}, TS Add/g {int((M.rk_tsaddg <= 5).sum())}, validated PAC/g **{int((M.rk_pacg <= 5).sum())}** of {len(M)}\n")
    out.append("| MVP | share | rTS | PPG rk | TS Add/g rk | validated PAC/g rk |\n|---|---|---|---|---|---|")
    for _, r in M.iterrows():
        out.append(f"| {r['name']} {lab(r.season)} | {r.l:.0%} | {r.rts:+.1f} | {r.rk_ppg} | {r.rk_tsaddg} | {r.rk_pacg} |")
    out.append("")

    # 4. hidden cost of an absence, current stars
    cur = q[q.season == 2025].sort_values("pacg", ascending=False).head(10)
    out.append("## 4. What a game without him costs his team's scoring, 2025-26 (points per game)\n")
    out.append("TS Add/g is the league-average-replacement answer; validated PAC/g adds the measured load term.\n")
    out.append("| player | share | league-average math (TS Add/g) | measured (validated PAC/g) | hidden cost |\n|---|---|---|---|---|")
    for _, r in cur.iterrows():
        out.append(f"| {r['name']} | {r.l:.0%} | {r.tsaddg:+.2f} | {r.pacg:+.2f} | {r.loadg:+.2f} |")
    out.append("")

    # 5. mechanism: what happens to the teammates' own shots
    import _pac_gamelevel as G
    A = G.assemble(ft_w=0.44, outcome="tsa", min_apps=10, min_den=4.0)
    P = A["P"]
    mech = res["mechanism"]
    out.append("## 5. The teammates' own shots\n")
    for Lc in (0.25, 0.30, 0.35):
        band = P[(P.L >= Lc - 0.02) & (P.L < Lc + 0.02)]
        Lf = float(band.L_full.median())
        key = f"gap{int(round(Lc * 100))}"
        rate = mech["rate"].get(key)
        mix = mech["mix"].get(key)
        if rate is None:   # 0.35 not stored: evaluate the linear rate schedule
            rate = mech["rate"]["c"] + mech["rate"]["s"] * Lc
            mix = mech["mix"]["c"] + mech["mix"]["s"] * Lc
        out.append(f"- absent player at {Lc:.0%} share (typically {Lf:.0%} of team attempts over whole games): the teammates' efficiency on "
                   f"**all** their shots falls about **{50 * Lf * rate:.1f} TS points**; the change in who shoots adds {50 * Lf * mix:.1f}.")
    out.append("")

    # 6. who carries load at all
    rot = P[P.n_apps >= 20]
    out.append("## 6. Who the load credit applies to\n")
    out.append(f"- rotation player-seasons (20+ games): {len(rot):,}; share below the {L0:.0%} threshold: **{(rot.L < L0).mean():.0%}**; "
               f"at 25%+: **{(rot.L >= 0.25).mean():.0%}**; at 30%+: **{(rot.L >= 0.30).mean():.1%}**")
    tot = q.assign(load=q.loadg * q.gp)
    top10 = tot.sort_values("load", ascending=False)
    share_top = top10.head(int(len(top10) * 0.10)).load.sum() / tot.load.sum()
    out.append(f"- the top 10% of qualified seasons by load credit hold **{share_top:.0%}** of all load credit\n")

    # 7. famous debates
    out.append("## 7. Debates the price settles differently\n")
    out.append("| season | share | rTS | PPG rk | TS Add/g rk | published PAC rk | validated PAC rk | of |\n|---|---|---|---|---|---|---|---|")
    for y, nm in ((2001, "Allen Iverson"), (2016, "Russell Westbrook"), (2016, "James Harden"), (2016, "Kawhi Leonard"),
                  (2010, "Derrick Rose"), (2012, "Carmelo Anthony"), (2016, "DeMar DeRozan"), (2007, "Steve Nash"),
                  (2011, "Tyson Chandler"), (2001, "Michael Jordan"), (2025, "Tyrese Maxey"), (2025, "Jalen Duren")):
        r = q[(q.season == y) & (q.name.str.contains(nm))]
        if len(r):
            r = r.iloc[0]
            out.append(f"| {r['name']} {lab(y)} | {r.l:.0%} | {r.rts:+.1f} | {r.rk_ppg} | {r.rk_tsaddg} | {r.rk_pubg} | {r.rk_pacg} | {r.n} |")
    txt = "\n".join(out)
    with open(os.path.join(HERE, "_pac_examples.md"), "w", encoding="utf-8") as f:
        f.write(txt)
    print(txt)


if __name__ == "__main__":
    main()
