# -*- coding: utf-8 -*-
"""_pac_boards.py -- PAC leaderboards: published schedule (0.25 L) vs validated hinge schedule.

    PAC = TS Add + TSA * gap(L),  per game.  Pool: >= 40 games and >= 2,500 on-court possessions.
    published: gap = 0.25 L        validated: gap = s_h * max(0, L - L0)  (from _pac_gamelevel_results.json)

Usage: python _pac_boards.py 2025 2007 2005 2015     (season start years)   -> _pac_boards.md
"""
import json
import os
import sys

import numpy as np
import pandas as pd

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
HERE = os.path.dirname(os.path.abspath(__file__))


def lab(y):
    return f"{y % 100:02d}-{(y + 1) % 100:02d}"


def board(y, s_h, L0, top=15, movers=6):
    code = f"{y % 100:02d}{(y + 1) % 100:02d}"
    with open(os.path.join(HERE, f"_sv_season_{code}.json"), encoding="utf-8") as f:
        S = pd.DataFrame(json.load(f)["rows"])
    q = S[(S.gp >= 40) & (S.poss >= 2500)].copy()
    q["ppg"] = q.pts / q.gp
    q["pub"] = (q.tsadd + q.tsa * 0.25 * q.l) / q.gp
    q["val"] = (q.tsadd + q.tsa * s_h * np.maximum(0.0, q.l - L0)) / q.gp
    q["tsaddg"] = q.tsadd / q.gp
    for c in ("ppg", "pub", "val", "tsaddg"):
        q[f"rk_{c}"] = q[c].rank(ascending=False, method="min").astype(int)
    q["move"] = q.rk_pub - q.rk_val          # positive = rises under the validated schedule
    n = len(q)
    out = [f"## {lab(y)}  (qualified: {n})\n",
           "| # | player | share | rTS | PPG (rk) | TS Add/g rk | PAC/g published (rk) | PAC/g validated | move |",
           "|---|---|---|---|---|---|---|---|---|"]
    for _, r in q.sort_values("val", ascending=False).head(top).iterrows():
        mv = f"+{r.move}" if r.move > 0 else (str(r.move) if r.move < 0 else "=")
        out.append(f"| {r.rk_val} | {r['name']} | {r.l:.0%} | {r.rts:+.1f} | {r.ppg:.1f} ({r.rk_ppg}) | {r.rk_tsaddg} | "
                   f"{r.pub:.2f} ({r.rk_pub}) | **{r.val:.2f}** | {mv} |")
    out.append("")
    ris = q.sort_values(["move", "val"], ascending=[False, False]).head(movers)
    fal = q.sort_values(["move", "val"], ascending=[True, False]).head(movers)
    out.append("Biggest risers: " + "; ".join(f"{r['name']} {r.rk_pub}→{r.rk_val} ({r.l:.0%} share)" for _, r in ris.iterrows()))
    out.append("")
    out.append("Biggest fallers: " + "; ".join(f"{r['name']} {r.rk_pub}→{r.rk_val} ({r.l:.0%} share)" for _, r in fal.iterrows()))
    out.append("")
    rho = q.rk_pub.corr(q.rk_val)
    top10 = len(set(q.nsmallest(10, "rk_pub").pid) & set(q.nsmallest(10, "rk_val").pid))
    out.append(f"Rank correlation {rho:.3f}; {top10} of the top 10 are the same; median |move| {q.move.abs().median():.0f} places.\n")
    return "\n".join(out), q


def main():
    years = [int(a) for a in sys.argv[1:]] or [2025, 2007]
    with open(os.path.join(HERE, "_pac_gamelevel_results.json"), encoding="utf-8") as f:
        h = json.load(f)["hinge"]
    s_h, L0 = h["s_h"], h["L0"]
    parts = [f"# PAC leaderboards: published (0.25 L) vs validated ({s_h:.3f} max(0, L - {L0:.2f}))\n",
             "Generated by `_pac_boards.py`. Pool >= 40 games and >= 2,500 possessions. `move` = places gained under the validated schedule.\n"]
    kobe = []
    for y in years:
        txt, q = board(y, s_h, L0)
        parts.append(txt)
    for y in (2005, 2006, 2007, 2015):
        _, q = board(y, s_h, L0)
        r = q[q.name.str.contains("Kobe Bryant")]
        if len(r):
            r = r.iloc[0]
            kobe.append(f"| {lab(y)} | {r.l:.0%} | {r.rts:+.1f} | {r.ppg:.1f} ({r.rk_ppg}) | {r.rk_tsaddg} | {r.pub:.2f} ({r.rk_pub}) | {r.val:.2f} ({r.rk_val}) | {len(q)} |")
    parts.append("## Kobe Bryant across seasons\n")
    parts.append("| season | share | rTS | PPG (rk) | TS Add/g rk | PAC/g published (rk) | PAC/g validated (rk) | of |\n|---|---|---|---|---|---|---|---|")
    parts += kobe
    txt = "\n".join(parts)
    with open(os.path.join(HERE, "_pac_boards.md"), "w", encoding="utf-8") as f:
        f.write(txt)
    print(txt)


if __name__ == "__main__":
    main()
