# -*- coding: utf-8 -*-
"""_pac_cases.py -- the headline PAC cases under each candidate price schedule.

PAC(schedule) = TS Add + TSA * gap(L),   TS Add = PTS - 2*lgTS*TSA,   L = season TSA / POSS.
Qualified pool: >= 40 games and >= 2,500 on-court possessions (6,315 player-seasons, 1997-98 .. 2025-26).
Ranks are per game within season unless stated.

Schedules (parameters read from _pac_gamelevel_results.json):
    published      gap = 0.25 L                       (PAC as released)
    origin         gap = s0 L                         (game-level, PAC's functional form)
    hinge          gap = s_h max(0, L - L0)           (game-level, threshold form)
    linear         gap = c + s L                      (game-level, free intercept, unclipped)
"""
import json
import os
import sys

import numpy as np
import pandas as pd

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
HERE = os.path.dirname(os.path.abspath(__file__))


def load_pool():
    rows = []
    for y in range(1997, 2026):
        code = f"{y % 100:02d}{(y + 1) % 100:02d}"
        with open(os.path.join(HERE, f"_sv_season_{code}.json"), encoding="utf-8") as f:
            d = json.load(f)
        for r in d["rows"]:
            r = dict(r)
            r["season"] = y
            rows.append(r)
    S = pd.DataFrame(rows)
    return S


def schedules(res):
    m, h = res["main"], res["hinge"]
    return {
        "published": lambda L: 0.25 * L,
        "origin": lambda L, s0=m["s_origin"]: s0 * L,
        "hinge": lambda L, s=h["s_h"], L0=h["L0"]: s * np.maximum(0.0, L - L0),
        "linear": lambda L, c=m["c"], s=m["s"]: c + s * L,
    }


def season_label(y):
    return f"{y % 100:02d}-{(y + 1) % 100:02d}"


def main():
    with open(os.path.join(HERE, "_pac_gamelevel_results.json"), encoding="utf-8") as f:
        res = json.load(f)
    S = load_pool()
    q = S[(S.gp >= 40) & (S.poss >= 2500)].copy()
    sch = schedules(res)
    for k, f in sch.items():
        q[f"pac_{k}"] = q.tsadd + q.tsa * f(q.l.values)
        q[f"pacg_{k}"] = q[f"pac_{k}"] / q.gp
        q[f"rk_{k}"] = q.groupby("season")[f"pacg_{k}"].rank(ascending=False, method="min")
    q["ppg"] = q.pts / q.gp
    q["tsaddg"] = q.tsadd / q.gp
    q["rk_ppg"] = q.groupby("season").ppg.rank(ascending=False, method="min")
    q["rk_tsadd"] = q.groupby("season").tsaddg.rank(ascending=False, method="min")
    q["n_season"] = q.groupby("season").pid.transform("size")

    L = ["# PAC headline cases under each price schedule\n",
         "Generated by `_pac_cases.py` from `_sv_season_*.json` and `_pac_gamelevel_results.json`. Qualified pool: >= 40 games and "
         f">= 2,500 possessions ({len(q):,} player-seasons). Ranks are per game within season.\n",
         "| schedule | gap(L) |\n|---|---|"]
    m, h = res["main"], res["hinge"]
    L.append("| published | 0.25 L |")
    L.append(f"| origin (game-level, PAC form) | {m['s_origin']:.3f} L |")
    L.append(f"| hinge (game-level) | {h['s_h']:.3f} max(0, L - {h['L0']:.2f}) |")
    L.append(f"| linear (game-level, free intercept) | {m['c']:.3f} + {m['s']:.3f} L |")
    L.append("")

    L.append("## Break-even relative TS (TS points below league at which PAC = 0)\n")
    L.append("| share L | " + " | ".join(sch) + " |\n|---|" + "---|" * len(sch))
    for Lv in (0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40):
        L.append(f"| {Lv:.2f} | " + " | ".join(f"{-50 * f(np.array(Lv)):+.1f}" for f in sch.values()) + " |")
    L.append("")

    def case(name_sub, season):
        r = q[(q.name.str.contains(name_sub)) & (q.season == season)]
        return r.iloc[0] if len(r) else None

    L.append("## Named player-seasons\n")
    L.append("| player-season | share L | rTS | PPG rank | TS Add/g rank | " + " | ".join(f"PAC rank ({k})" for k in sch) + " | of |")
    L.append("|---|---|---|---|---|" + "---|" * len(sch) + "---|")
    for nm, yr in (("Allen Iverson", 2001), ("Allen Iverson", 2000), ("Russell Westbrook", 2016), ("Kobe Bryant", 2005),
                   ("Luka", 2025), ("DeMar DeRozan", 2016), ("Jaylen Brown", 2025), ("Shai Gilgeous", 2025),
                   ("Nikola Jok", 2025), ("Tyson Chandler", 2011), ("Stephen Curry", 2015), ("Michael Jordan", 2001)):
        r = case(nm, yr)
        if r is None:
            continue
        L.append(f"| {r['name']} {season_label(yr)} | {r['l']:.3f} | {r['rts']:+.1f} | {int(r['rk_ppg'])} | {int(r['rk_tsadd'])} | "
                 + " | ".join(str(int(r[f'rk_{k}'])) for k in sch) + f" | {int(r['n_season'])} |")
    L.append("")

    L.append("## DeMar DeRozan, Toronto 2009-10 to 2017-18 (season sums, all games)\n")
    dr = S[(S.name.str.contains("DeMar DeRozan")) & (S.season.between(2009, 2017))]
    L.append("| quantity | value |\n|---|---|")
    L.append(f"| TS Add | {dr.tsadd.sum():+.0f} |")
    for k, f in sch.items():
        L.append(f"| PAC ({k}) | {(dr.tsadd + dr.tsa * f(dr.l.values)).sum():+.0f} |")
    L.append("")

    L.append("## Seasons at >= 30% share below break-even (PAC < 0)\n")
    hi = q[q.l >= 0.30]
    L.append(f"{len(hi)} qualified seasons at L >= 0.30.\n")
    L.append("| schedule | below break-even | who |\n|---|---|---|")
    for k in sch:
        b = hi[hi[f"pac_{k}"] < 0].sort_values(f"pac_{k}")
        who = ", ".join(f"{r['name']} {season_label(r['season'])}" for _, r in b.iterrows())
        L.append(f"| {k} | {len(b)} | {who} |")
    L.append("")

    L.append("## All-time top 10, PAC per game\n")
    for k in ("published", "hinge"):
        top = q.sort_values(f"pacg_{k}", ascending=False).head(10)
        L.append(f"**{k}:** " + "; ".join(f"{r['name']} {season_label(r['season'])} {r[f'pacg_{k}']:.2f}" for _, r in top.iterrows()) + "\n")

    L.append("## How much the schedule choice moves rankings\n")
    L.append("| pair | Spearman, PAC/g within season (mean over seasons) | seasons where the #1 changes |\n|---|---|---|")
    keys = list(sch)
    for i in range(len(keys)):
        for j in range(i + 1, len(keys)):
            a, b = keys[i], keys[j]
            rhos, ch = [], 0
            for _, g in q.groupby("season"):
                rhos.append(g[f"pacg_{a}"].rank().corr(g[f"pacg_{b}"].rank()))
                ch += int(g.loc[g[f"pacg_{a}"].idxmax(), "pid"] != g.loc[g[f"pacg_{b}"].idxmax(), "pid"])
            L.append(f"| {a} vs {b} | {np.mean(rhos):.3f} | {ch} of {q.season.nunique()} |")
    L.append("")
    txt = "\n".join(L)
    with open(os.path.join(HERE, "_pac_cases_results.md"), "w", encoding="utf-8") as f:
        f.write(txt)
    print(txt)


if __name__ == "__main__":
    main()
